server:
  port: 2016
spring:
  cloud:
    bootstrap:
      enabled: false
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.101:3306/hikari_test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      max-lifetime: 900000
  application:
    name: test-consumer
  zipkin:
    sender:
      type: kafka
  sleuth:
    enabled: false
    traceId128: true
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 192.168.100.101:9092