server:
  port: 2016
spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  dubbo:
    provider:
      filter: 'tracing'
    consumer:
      filter: 'tracing'

dubbo:
  application:
    name: consumer
    id: consumer
    qos:
      enable: 'false'
  registry:
    protocol: zookeeper
    address: 192.168.100.101:2181
    client: curator
    id: test
  consumer:
    filter: 'tracing'
