server:
  port: 2016
spring:
  application:
    name: test-consumer
  zipkin:
    sender:
      type: kafka
  sleuth:
    feign:
      enabled: true
    enabled: true
    traceId128: true
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 192.168.100.101:9092

dubbo:
  application:
    name: test-consumer
    id: test-consumer
  registry:
    address: zookeeper://192.168.100.101:2181
    client: curator
    id: test
  consumer:
    filter: 'tracing'
