server:
  port: 2016
spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    traceId128: true
    sampler:
      probability: 1.0

dubbo:
  application:
    name: consumer
    id: consumer
  registry:
    address: zookeeper://192.168.100.101:2181
    client: curator
    id: test
  consumer:
    filter: 'tracing'
